version: 2

workflows:
  version: 2
  pipeline:
    jobs:
      - py-qa
      - docs
      - py36-dj20
      - js-qa
      - js-qa-nightwatch-with-saucelabs

jobs:
  docs:
    docker:
    - image: circleci/node:9
    steps:
    - checkout
    - restore_cache:
        keys:
        - qa-dependencies-{{ checksum "tox.ini" }}
    - run:
        name: tox environment setup
        command: |
          set -eux
          sudo apt install -y python3-pip
          sudo pip3 install tox
          sudo npm install -g jsdoc
          tox -r -e docs --notest
    - save_cache:
        paths: [~/.cache/pip]
        key: qa-dependencies-{{ checksum "tox.ini" }}
    - run:
        name: try docs build
        command: tox -e docs

  py-qa:
    docker:
    - image: circleci/python:3.6
    steps:
    - checkout
    - restore_cache:
        keys:
        - qa-dependencies-{{ checksum "tox.ini" }}
    - run:
        name: tox environment setup
        command: pip install --user tox && ~/.local/bin/tox -r -e qa --notest
    - save_cache:
        paths: [~/.local, ~/.cache/pip]
        key: qa-dependencies-{{ checksum "tox.ini" }}
    - run:
        name: run qa checks
        command: ~/.local/bin/tox -e qa

  py36-dj20:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - test-dependencies-{{ checksum "tox.ini" }}
    - run:
        name: Tox environment setup
        command: pip install --user tox && ~/.local/bin/tox -r -e py36-dj20 --notest
    - save_cache:
        paths: [~/.local, ~/.cache/pip]
        key: test-dependencies-{{ checksum "tox.ini" }}
    - run:
        name: TEST tox -e py36-dj20
        command: |
          ~/.local/bin/tox -e py36-dj20
          PATH=./.tox/py36-dj20/bin:$PATH codecov -e $TOXENV

  js-qa:
    docker:
    - image: circleci/node:8
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: RUN yarn install
        command: yarn install
    - run:
        name: RUN yarn run lint
        command: yarn run lint

  js-test:
    docker:
    - image: circleci/node:8
    working_directory: ~/repo/src/crudlfap
    steps:
    - checkout
    - run:
        name: RUN yarn install
        command: yarn install
    - run:
        name: RUN yarn test & coverage upload
        command: yarn test && ./node_modules/.bin/codecov

  js-qa-nightwatch:
    docker:
    - image: circleci/node:8
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: RUN sudo apt install default-jre
        command: sudo apt install default-jre
    - run:
        name: RUN yarn run browser-test
        command: yarn run browser-test


  js-qa-nightwatch-with-saucelabs:
    docker:
    - image: circleci/node:8
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: Start SauceLabs Tunnel (required if testing on CircleCI container)
        command: |
            curl https://saucelabs.com/downloads/sc-4.4.12-linux.tar.gz -o saucelabs.tar.gz
            tar -xzf saucelabs.tar.gz
    - run:
        name: Setup 1
        command: |
            cd sc-*-linux &&  ./bin/sc -u navjot.g -k f817b186-0804-45a3-bdff-597eafc9da7
    - run:
        name: Setup 2
        command: |
            "while ! lsof -i:4445 -t; do sleep 3; done"
    - run:
        name: RUN yarn run browser-test
        command: yarn run browser-test
